### ISSUE TITLE
Can you open images from URLs?

### ISSUE THREAD

**Issue by kojix2** [yoshoku/magro#2]
Hello. @yoshoku 

Thank you for all your wonderful work.

I want to open images on the internet from URLs with Magro.
(I tried to display [Ghibli images](https://www.ghibli.jp/info/013409/) in [LibUI](https://github.com/kojix2/LibUI) window using magro.)

![image](https://user-images.githubusercontent.com/5798442/105567709-614f2400-5d77-11eb-97a4-a78b32638880.png)

But I couldn't find a way to do it, so [I used chunky_png](
https://github.com/kojix2/LibUI/blob/a60b98a07440711527df2d4c50e725dc3d40f3c8/examples/basic_table_image.rb#L22-L30).

```ruby
  url = format('https://www.ghibli.jp/gallery/thumb-redturtle%03d.png', (i + 1))
  f = URI.open(url)
  canvas = ChunkyPNG::Canvas.from_io(f)
  f.close
  data = canvas.to_rgba_stream
  width = canvas.width
  height = canvas.height
  image = UI.new_image(width, height)
  UI.image_append(image, data, width, height, width * 4)
```

Is it possible to open an image from a URL?
If you don't have that feature, I would love to have it.

**Comment by yoshoku** [comment]
@kojix2 
As you know, Magro::IO.imread can only read local files. I suggest saving an image on the Internet to a temporary file and loading it.

```ruby
require 'open-uri'
require 'tempfile'
require 'magro'

def imread_url(url, ext: '.png')
  URI.open(url) do |file|
    temp = Tempfile.new(['', ext])
    temp.binmode
    temp.write(file.read)
    temp.rewind
    Magro::IO.imread(temp.path)
  end
end

i = 0
url = format('https://www.ghibli.jp/gallery/thumb-redturtle%03d.png', (i + 1))
pp imread_url(url)
```
```sh
$ ruby imread_url.rb
Numo::UInt8#shape=[162,300,3]
[[[37, 79, 21],
  [43, 89, 24],
  [45, 93, 25],
....
```

**Comment by kojix2** [comment]
What I was thinking was that

(1) Ruby reads a binary string from the Internet.
(2) The ruby string is converted to a C string.
(3) libpng and libjpeg read the data from memory.

However, I don't have any C skills.
I cannot tell if this is possible or not.

It's not going to be easy, is it?

**Comment by yoshoku** [comment]
(1)
```ruby
require 'open-uri'
str = URI.open(url) { |file| file.read }
```
(2)
```c
static VALUE read_png_from_str(VALUE self, VALUE str_)
{
  char* str = StringValuePtr(str_);
  
  ...
}
```
(3)
I have never try that. It may be written in the official documentation.
http://www.libpng.org/pub/png/pngdocs.html

Your question does not seem to be about Magro's problem, so it is not appropriate to discuss that here, I would like to close this issue.

**Comment by kojix2** [comment]
To read an image from a URL and convert it to Numo::NArray.
This means reading a png or jpeg image from a Ruby IO object or binary string.
In Magro, the file name is passed to C at the Ruby level, and C reads the file. It is probably possible to read a png or jpeg image from a memory buffer, but implementing this is a future issue or a feature that Magro will not do. 

I think this isssue is about Magro. I understood it as above.

**Comment by yoshoku** [comment]
I would like to consider reading images from URLs in the future. Thank you for your understanding.

**Comment by kojix2** [comment]
I have confirmed that it works with the following commit.
https://github.com/yoshoku/magro/commit/90ce768534f118110a6edb0fdbf2bcd41fc0c662

(I think it would be really cool if you could read directly from memory, though...  )
